Update path
This is so that the integration test is able to find the n-ui-foundations, which is not inside the @Financial-Times folder. This was in response to the error below.

Error: Can't find stylesheet to import.
      ╷
    1 │ @import "n-ui-foundations/mixins";
      │         ^^^^^^^^^^^^^^^^^^^^^^^^^
      ╵
      main.scss 1:9                         @import
      test/integration/entry-file.scss 3:9  root stylesheet